export type StorageNodeKind='property'|'building'|'room'|'zone'|'cabinet'|'shelf'|'drawer'|'bin'|'case'|'custom';
export type CapacityUnit='items'|'volume'|'weight'|'custom';
export type StorageNode={id:string;name:string;kind:StorageNodeKind;parentId:string|null;archived:boolean;position:number;capacityLimit:number|null;capacityUnit:CapacityUnit;strictCapacity:boolean;createdAt:string;updatedAt:string};
export type StorageAssignment={itemId:string;nodeId:string;assignedAt:string};
export type StorageMove={id:string;itemId:string;fromNodeId:string|null;toNodeId:string;movedAt:string;note?:string};
export type CapacityStatus={used:number;limit:number|null;remaining:number|null;percent:number|null;warning:boolean;overCapacity:boolean};
export type BulkMovePlan={assignments:StorageAssignment[];moves:StorageMove[];warnings:string[]};

const uid=(prefix:string)=>`${prefix}_${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`}`;
const now=()=>new Date().toISOString();
const checksum=(value:string)=>{let h=2166136261;for(const c of value){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};

export function createNode(input:Partial<StorageNode>&Pick<StorageNode,'name'|'kind'>):StorageNode{const stamp=now();return{id:input.id??uid('loc'),name:input.name.trim(),kind:input.kind,parentId:input.parentId??null,archived:input.archived??false,position:input.position??0,capacityLimit:input.capacityLimit??null,capacityUnit:input.capacityUnit??'items',strictCapacity:input.strictCapacity??false,createdAt:input.createdAt??stamp,updatedAt:stamp}}
export function nodeMap(nodes:StorageNode[]):Map<string,StorageNode>{return new Map(nodes.map(node=>[node.id,node]))}
export function descendants(nodes:StorageNode[],nodeId:string):Set<string>{const result=new Set<string>();let changed=true;while(changed){changed=false;for(const node of nodes){if(!result.has(node.id)&&(node.parentId===nodeId||(node.parentId&&result.has(node.parentId)))){result.add(node.id);changed=true}}}return result}
export function validateMove(nodes:StorageNode[],nodeId:string,newParentId:string|null):void{const map=nodeMap(nodes);const node=map.get(nodeId);if(!node)throw new Error('Storage node not found');if(newParentId===nodeId)throw new Error('A location cannot be its own parent');if(newParentId){const parent=map.get(newParentId);if(!parent)throw new Error('Destination location not found');if(parent.archived)throw new Error('Archived locations cannot receive children');if(descendants(nodes,nodeId).has(newParentId))throw new Error('Move would create a storage cycle')}}
export function moveNode(nodes:StorageNode[],nodeId:string,newParentId:string|null):StorageNode[]{validateMove(nodes,nodeId,newParentId);const stamp=now();return nodes.map(node=>node.id===nodeId?{...node,parentId:newParentId,updatedAt:stamp}:node)}
export function archiveNode(nodes:StorageNode[],nodeId:string):StorageNode[]{if(descendants(nodes,nodeId).size>0)throw new Error('Move or archive child locations first');return nodes.map(node=>node.id===nodeId?{...node,archived:true,updatedAt:now()}:node)}
export function buildBreadcrumb(nodes:StorageNode[],nodeId:string):StorageNode[]{const map=nodeMap(nodes);const path:StorageNode[]=[];const seen=new Set<string>();let current=map.get(nodeId);while(current){if(seen.has(current.id))throw new Error('Storage hierarchy contains a cycle');seen.add(current.id);path.unshift(current);current=current.parentId?map.get(current.parentId):undefined}return path}
export function calculateCapacity(node:StorageNode,assignments:StorageAssignment[],nodes:StorageNode[]=[]):CapacityStatus{const scope=new Set([node.id,...descendants(nodes,node.id)]);const used=assignments.filter(a=>scope.has(a.nodeId)).length;const limit=node.capacityLimit;const percent=limit&&limit>0?Math.round((used/limit)*100):null;return{used,limit,remaining:limit==null?null:limit-used,percent,warning:percent!=null&&percent>=80,overCapacity:limit!=null&&used>limit}}
export function planBulkAssignmentMove(itemIds:string[],toNodeId:string,nodes:StorageNode[],assignments:StorageAssignment[],note?:string):BulkMovePlan{const destination=nodeMap(nodes).get(toNodeId);if(!destination)throw new Error('Destination location not found');if(destination.archived)throw new Error('Archived locations cannot receive items');const unique=[...new Set(itemIds)];const current=new Map(assignments.map(a=>[a.itemId,a]));const projected=assignments.filter(a=>!unique.includes(a.itemId));const stamp=now();const moved=unique.map(itemId=>({itemId,nodeId:toNodeId,assignedAt:stamp}));const status=calculateCapacity(destination,[...projected,...moved],nodes);if(destination.strictCapacity&&status.overCapacity)throw new Error('Destination capacity would be exceeded');const moves=unique.map(itemId=>({id:uid('move'),itemId,fromNodeId:current.get(itemId)?.nodeId??null,toNodeId,movedAt:stamp,note}));return{assignments:[...projected,...moved],moves,warnings:status.warning?[status.overCapacity?'Destination is over capacity':'Destination is nearing capacity']:[]}}
export function encodeStorageQr(installationId:string,nodeId:string):string{const body=`v1|${installationId}|${nodeId}`;return `vault-storage:${body}|${checksum(body)}`}
export function decodeStorageQr(payload:string,installationId?:string):{version:1;installationId:string;nodeId:string}{if(!payload.startsWith('vault-storage:'))throw new Error('Unsupported storage QR payload');const parts=payload.slice(14).split('|');if(parts.length!==4||parts[0]!=='v1')throw new Error('Malformed storage QR payload');const body=parts.slice(0,3).join('|');if(checksum(body)!==parts[3])throw new Error('Storage QR checksum mismatch');if(installationId&&parts[1]!==installationId)throw new Error('Storage QR belongs to another Vault installation');return{version:1,installationId:parts[1],nodeId:parts[2]}}
export function searchLocations(nodes:StorageNode[],query:string):StorageNode[]{const needle=query.trim().toLowerCase();return nodes.filter(node=>!node.archived&&(!needle||`${node.name} ${node.kind}`.toLowerCase().includes(needle)))}