import React from 'react';
import type{ItemRecord}from'@vault/domain';
import{buildBreadcrumb,calculateCapacity,createNode,decodeStorageQr,encodeStorageQr,planBulkAssignmentMove,type StorageAssignment,type StorageMove,type StorageNode,type StorageNodeKind}from'@vault/storage-management';

const KEY='vault-storage-management-v1';
type State={installationId:string;nodes:StorageNode[];assignments:StorageAssignment[];moves:StorageMove[]};
const initial=(items:ItemRecord[]):State=>{const installationId=crypto.randomUUID();const root=createNode({name:'My Property',kind:'property'});const nodes=[root];const assignments:StorageAssignment[]=[];for(const item of items){const parts=(item.specifics.storagePath??'').split(/[/>]/).map(v=>v.trim()).filter(Boolean);let parent=root.id;for(const [index,name] of parts.entries()){let node=nodes.find(n=>n.parentId===parent&&n.name===name);if(!node){node=createNode({name,kind:index===parts.length-1?'bin':'room',parentId:parent});nodes.push(node)}parent=node.id}if(parts.length)assignments.push({itemId:item.id,nodeId:parent,assignedAt:new Date().toISOString()})}return{installationId,nodes,assignments,moves:[]}};
const load=(items:ItemRecord[]):State=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):initial(items)}catch{return initial(items)}};
const download=(name:string,data:string,type='text/plain')=>{const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};

export function StorageManager({items,onAssign}:{items:ItemRecord[];onAssign:(itemIds:string[],node:StorageNode,path:string)=>Promise<void>}){
 const[state,setState]=React.useState<State>(()=>load(items));const[selectedNode,setSelectedNode]=React.useState(state.nodes[0]?.id??'');const[selectedItems,setSelectedItems]=React.useState<Set<string>>(new Set());const[name,setName]=React.useState('');const[kind,setKind]=React.useState<StorageNodeKind>('bin');const[capacity,setCapacity]=React.useState('');const[scan,setScan]=React.useState('');const[error,setError]=React.useState<string|null>(null);
 React.useEffect(()=>localStorage.setItem(KEY,JSON.stringify(state)),[state]);const active=state.nodes.find(n=>n.id===selectedNode)??state.nodes[0];const children=(parentId:string|null)=>state.nodes.filter(n=>n.parentId===parentId&&!n.archived).sort((a,b)=>a.position-b.position||a.name.localeCompare(b.name));const assignedAt=(nodeId:string)=>state.assignments.filter(a=>a.nodeId===nodeId).map(a=>items.find(i=>i.id===a.itemId)).filter(Boolean)as ItemRecord[];
 function addNode(){if(!name.trim())return;const node=createNode({name,kind,parentId:active?.id??null,capacityLimit:capacity?Number(capacity):null});setState(s=>({...s,nodes:[...s.nodes,node]}));setSelectedNode(node.id);setName('');setCapacity('')}
 async function moveSelected(){if(!active||selectedItems.size===0)return;try{setError(null);const plan=planBulkAssignmentMove([...selectedItems],active.id,state.nodes,state.assignments,'Desktop bulk relocation');const path=buildBreadcrumb(state.nodes,active.id).map(n=>n.name).join(' / ');await onAssign([...selectedItems],active,path);setState(s=>({...s,assignments:plan.assignments,moves:[...s.moves,...plan.moves]}));setSelectedItems(new Set())}catch(e){setError(String(e))}}
 function exportQr(){if(!active)return;download(`vault-location-${active.name.replace(/\W+/g,'-')}.txt`,encodeStorageQr(state.installationId,active.id))}
 function scanQr(){try{const decoded=decodeStorageQr(scan,state.installationId);if(!state.nodes.some(n=>n.id===decoded.nodeId))throw new Error('Location is not present in this Vault');setSelectedNode(decoded.nodeId);setScan('');setError(null)}catch(e){setError(String(e))}}
 const render=(parentId:string|null,depth=0):React.ReactNode=>children(parentId).map(node=>{const cap=calculateCapacity(node,state.assignments,state.nodes);return <React.Fragment key={node.id}><button className={node.id===selectedNode?'storage-node active':'storage-node'} style={{paddingLeft:12+depth*18}} onClick={()=>setSelectedNode(node.id)}><span>{node.kind}</span><b>{node.name}</b><small>{cap.used}{cap.limit!=null?` / ${cap.limit}`:''}{cap.warning?' ⚠':''}</small></button>{render(node.id,depth+1)}</React.Fragment>});
 const unassigned=items.filter(item=>!state.assignments.some(a=>a.itemId===item.id));
 return <section className="storage-manager"><aside className="panel storage-nav"><div className="marketplace-head"><div><p className="eyebrow">PHYSICAL DIGITAL TWIN</p><h3>Locations</h3></div></div><div className="storage-node-list">{render(null)}</div><div className="storage-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New location name"/><select value={kind} onChange={e=>setKind(e.target.value as StorageNodeKind)}>{['property','building','room','zone','cabinet','shelf','drawer','bin','case','custom'].map(v=><option key={v}>{v}</option>)}</select><input value={capacity} onChange={e=>setCapacity(e.target.value)} inputMode="numeric" placeholder="Capacity (optional)"/><button className="primary" onClick={addNode}>Add below selected</button></div></aside><main className="panel storage-detail">{error&&<div className="banner error">{error}</div>}{active&&<><div className="marketplace-head"><div><p className="eyebrow">{buildBreadcrumb(state.nodes,active.id).map(n=>n.name).join(' / ')}</p><h3>{active.name}</h3></div><button className="secondary" onClick={exportQr}>Export QR payload</button></div><div className="valuation-cards"><article><span>Direct items</span><strong>{assignedAt(active.id).length}</strong></article><article><span>Total occupancy</span><strong>{calculateCapacity(active,state.assignments,state.nodes).used}</strong></article><article><span>Capacity</span><strong>{active.capacityLimit??'Unlimited'}</strong></article><article><span>Move history</span><strong>{state.moves.filter(m=>m.toNodeId===active.id||m.fromNodeId===active.id).length}</strong></article></div><div className="scan-row"><input value={scan} onChange={e=>setScan(e.target.value)} placeholder="Paste or scan Vault location QR payload"/><button className="secondary" onClick={scanQr}>Open scanned location</button></div><h4>Items at this location</h4><div className="storage-items">{assignedAt(active.id).map(item=><div key={item.id}><b>{item.title}</b><small>{item.sku||item.category}</small></div>)}{assignedAt(active.id).length===0&&<p className="empty-note">No items directly assigned.</p>}</div><h4>Unassigned inventory / bulk move</h4><div className="storage-items selectable">{unassigned.map(item=><label key={item.id}><input type="checkbox" checked={selectedItems.has(item.id)} onChange={e=>setSelectedItems(cur=>{const next=new Set(cur);e.target.checked?next.add(item.id):next.delete(item.id);return next})}/><span><b>{item.title}</b><small>{item.category}</small></span></label>)}</div><button className="primary" disabled={!selectedItems.size} onClick={moveSelected}>Move {selectedItems.size||''} item(s) here</button></>}</main></section>;
}