export type CaptureJobType='thumbnail'|'quality'|'ocr'|'barcode'|'duplicate'|'classify'|'sync';
export type CaptureJobStatus='queued'|'running'|'completed'|'failed'|'cancelled';
export type CaptureJob={id:string;type:CaptureJobType;itemId?:string;photoId?:string;status:CaptureJobStatus;progress:number;attempts:number;maxAttempts:number;createdAt:string;updatedAt:string;error?:string;payload:Record<string,unknown>};
export type PhotoAsset={id:string;itemId?:string;name:string;dataUrl:string;width:number;height:number;sizeBytes:number;mimeType:string;createdAt:string;primary:boolean;quality?:PhotoQuality;perceptualHash?:string};
export type PhotoQuality={score:number;sharpness:number;exposure:number;resolution:number;warnings:string[]};
export type PairingSession={id:string;code:string;token:string;desktopName:string;createdAt:string;expiresAt:string;pairedAt?:string;deviceName?:string};
export type OfflineCapture={id:string;createdAt:string;title?:string;photos:PhotoAsset[];notes?:string;status:'pending'|'syncing'|'synced'|'failed';attempts:number;error?:string};
const now=()=>new Date().toISOString();
const uid=(prefix:string)=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`;
export function createJob(type:CaptureJobType,payload:Record<string,unknown>={},refs:{itemId?:string;photoId?:string}={}):CaptureJob{const t=now();return{id:uid('job'),type,status:'queued',progress:0,attempts:0,maxAttempts:3,createdAt:t,updatedAt:t,payload,...refs}}
export function startJob(job:CaptureJob):CaptureJob{return{...job,status:'running',attempts:job.attempts+1,progress:Math.max(job.progress,1),updatedAt:now(),error:undefined}}
export function updateJobProgress(job:CaptureJob,progress:number):CaptureJob{return{...job,progress:Math.max(0,Math.min(100,Math.round(progress))),updatedAt:now()}}
export function completeJob(job:CaptureJob):CaptureJob{return{...job,status:'completed',progress:100,updatedAt:now(),error:undefined}}
export function failJob(job:CaptureJob,error:string):CaptureJob{return{...job,status:job.attempts<job.maxAttempts?'queued':'failed',progress:0,updatedAt:now(),error}}
export function cancelJob(job:CaptureJob):CaptureJob{return job.status==='completed'?job:{...job,status:'cancelled',updatedAt:now()}}
export function nextRunnableJob(jobs:CaptureJob[]):CaptureJob|undefined{return jobs.filter(j=>j.status==='queued'&&j.attempts<j.maxAttempts).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))[0]}
export function summarizeQueue(jobs:CaptureJob[]){return jobs.reduce((a,j)=>{a.total++;a[j.status]++;return a},{total:0,queued:0,running:0,completed:0,failed:0,cancelled:0} as Record<'total'|CaptureJobStatus,number>)}
export function createPairingSession(desktopName='Vault Desktop',ttlMinutes=10):PairingSession{const created=new Date();const expires=new Date(created.getTime()+ttlMinutes*60000);return{id:uid('pair'),code:String(Math.floor(100000+Math.random()*900000)),token:cryptoSafeToken(),desktopName,createdAt:created.toISOString(),expiresAt:expires.toISOString()}}
function cryptoSafeToken(){const bytes=new Uint8Array(24);globalThis.crypto?.getRandomValues?.(bytes);if(bytes.every(v=>v===0))for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);return Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join('')}
export function acceptPairing(session:PairingSession,code:string,deviceName:string,at=new Date()):PairingSession{if(session.pairedAt)throw new Error('Pairing session already used.');if(at.getTime()>Date.parse(session.expiresAt))throw new Error('Pairing code expired.');if(code.trim()!==session.code)throw new Error('Invalid pairing code.');return{...session,pairedAt:at.toISOString(),deviceName:deviceName.trim()||'Phone'}}
export function isPairingActive(session:PairingSession,at=new Date()){return!session.pairedAt&&at.getTime()<=Date.parse(session.expiresAt)}
export function analyzePhoto(input:{width:number;height:number;sizeBytes:number;brightness?:number;sharpness?:number}):PhotoQuality{const pixels=input.width*input.height;const resolution=Math.min(100,Math.round(pixels/12000000*100));const sharpness=Math.max(0,Math.min(100,Math.round(input.sharpness??Math.min(100,input.sizeBytes/Math.max(1,pixels)*140))));const brightness=input.brightness??50;const exposure=Math.max(0,100-Math.abs(50-brightness)*2);const score=Math.round(resolution*.35+sharpness*.4+exposure*.25);const warnings:string[]=[];if(resolution<45)warnings.push('Low resolution');if(sharpness<45)warnings.push('Image may be blurry');if(brightness<20)warnings.push('Image is underexposed');if(brightness>80)warnings.push('Image is overexposed');return{score,sharpness,exposure,resolution,warnings}}
export function differenceHash(samples:number[],size=64){if(samples.length<size)throw new Error(`Expected at least ${size} luminance samples.`);let bits='';for(let i=0;i<size;i++)bits+=samples[i]>=samples[(i+1)%size]?'1':'0';return BigInt(`0b${bits}`).toString(16).padStart(Math.ceil(size/4),'0')}
export function hammingDistance(a:string,b:string){const width=Math.max(a.length,b.length);let x=BigInt(`0x${a.padStart(width,'0')}`)^BigInt(`0x${b.padStart(width,'0')}`),n=0;while(x){n+=Number(x&1n);x>>=1n}return n}
export function duplicateConfidence(a:string,b:string,bits=64){return Math.max(0,Math.round((1-hammingDistance(a,b)/bits)*100))}
export function findDuplicates(photos:PhotoAsset[],threshold=90){const matches:{a:string;b:string;confidence:number}[]=[];for(let i=0;i<photos.length;i++)for(let j=i+1;j<photos.length;j++){const a=photos[i].perceptualHash,b=photos[j].perceptualHash;if(!a||!b)continue;const confidence=duplicateConfidence(a,b);if(confidence>=threshold)matches.push({a:photos[i].id,b:photos[j].id,confidence})}return matches.sort((x,y)=>y.confidence-x.confidence)}
export function inferItem(text:string){const normalized=text.replace(/\s+/g,' ').trim();const rules=[[/milwaukee|m18|m12/i,'tools'],[/pokemon|yu-gi-oh|magic|topps|panini/i,'cards'],[/iphone|ipad|macbook|samsung|sony|model\s*no/i,'electronics'],[/nike|adidas|jordan|size\s*\d/i,'shoes'],[/sterling|karat|\b14k\b|\b18k\b/i,'jewelry'],[/vin\b|engine|transmission|oem/i,'automotive']];const category=rules.find(([r])=>(r as RegExp).test(normalized))?.[1] as string|undefined;const brands=['Milwaukee','DeWalt','Makita','Apple','Samsung','Sony','Nike','Adidas','Jordan','Panini','Topps','Pokemon','Yu-Gi-Oh'];const brand=brands.find(b=>new RegExp(`\\b${b.replace('-','[- ]?')}\\b`,'i').test(normalized));const model=normalized.match(/(?:model|m\/n|part|sku)\s*[:#-]?\s*([A-Z0-9][A-Z0-9-]{2,})/i)?.[1];return{category:category??'other',brand,model,confidence:Math.min(95,45+(category?25:0)+(brand?15:0)+(model?10:0))}}
export function createOfflineCapture(input:Omit<OfflineCapture,'id'|'createdAt'|'status'|'attempts'>):OfflineCapture{return{id:uid('capture'),createdAt:now(),status:'pending',attempts:0,...input}}
export function beginOfflineSync(capture:OfflineCapture):OfflineCapture{return{...capture,status:'syncing',attempts:capture.attempts+1,error:undefined}}
export function finishOfflineSync(capture:OfflineCapture):OfflineCapture{return{...capture,status:'synced',error:undefined}}
export function failOfflineSync(capture:OfflineCapture,error:string):OfflineCapture{return{...capture,status:'failed',error}}
export function serializeCaptureBundle(captures:OfflineCapture[],device:{id:string;name:string}){return JSON.stringify({format:'vault-capture-bundle',version:1,createdAt:now(),device,captures})}
export function parseCaptureBundle(json:string){const value=JSON.parse(json);if(value?.format!=='vault-capture-bundle'||value?.version!==1||!Array.isArray(value.captures))throw new Error('Invalid Vault capture bundle.');return value as{format:'vault-capture-bundle';version:1;createdAt:string;device:{id:string;name:string};captures:OfflineCapture[]}}
