import type { ItemRecord } from '@vault/domain';
import type { ItemDraft } from '../../lib/catalogueApi';

export type ItemFormState = {
  title:string; category:string; subcategory:string; condition:string; conditionNotes:string; brand:string; model:string;
  year:string; edition:string; sku:string; serialNumber:string; description:string; notes:string; purchasePrice:string;
  medianValue:string; suggestedPrice:string; minimumPrice:string; quantity:string; status:'private'|'draft'|'listed'|'sold'|'archived';
  storagePath:string; tags:string; photos:string[]; specifics:Record<string,string>; protectedFields:string[]; inferredFields:string[];
};

export const emptyItemForm:ItemFormState={title:'',category:'cards',subcategory:'',condition:'Good',conditionNotes:'',brand:'',model:'',year:'',edition:'',sku:'',serialNumber:'',description:'',notes:'',purchasePrice:'',medianValue:'',suggestedPrice:'',minimumPrice:'',quantity:'1',status:'private',storagePath:'',tags:'',photos:[],specifics:{},protectedFields:[],inferredFields:[]};

const parseJsonArray=(value?:string)=>{try{const parsed=JSON.parse(value??'[]');return Array.isArray(parsed)?parsed.filter(v=>typeof v==='string'):[]}catch{return[]}};
export function itemToForm(item:ItemRecord):ItemFormState{return{title:item.title,category:item.category,subcategory:item.subcategory??'',condition:item.condition,conditionNotes:item.conditionNotes??'',brand:item.brand??'',model:item.model??'',year:item.year?.toString()??'',edition:item.edition??'',sku:item.sku??'',serialNumber:item.serialNumber??'',description:item.description??'',notes:item.notes??'',purchasePrice:item.purchasePrice?(item.purchasePrice.amountMinor/100).toFixed(2):'',medianValue:item.medianValue?(item.medianValue.amountMinor/100).toFixed(2):'',suggestedPrice:item.suggestedPrice?(item.suggestedPrice.amountMinor/100).toFixed(2):'',minimumPrice:item.minimumPrice?(item.minimumPrice.amountMinor/100).toFixed(2):'',quantity:String(item.quantity),status:item.status,storagePath:item.specifics.storagePath??'',tags:parseJsonArray(item.specifics.tags).join(', '),photos:parseJsonArray(item.specifics.photos),specifics:{...item.specifics},protectedFields:parseJsonArray(item.specifics.__protectedFields),inferredFields:[]}};
const money=(value:string)=>{const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=0?{amountMinor:Math.round(parsed*100),currency:'USD'}:null};
export function formToDraft(form:ItemFormState):ItemDraft{return{title:form.title.trim(),category:form.category,subcategory:form.subcategory.trim()||null,condition:form.condition.trim(),conditionNotes:form.conditionNotes.trim()||null,status:form.status,quantity:Math.max(1,Number.parseInt(form.quantity||'1',10)||1),brand:form.brand.trim()||null,model:form.model.trim()||null,year:form.year.trim()?Number.parseInt(form.year,10):null,edition:form.edition.trim()||null,sku:form.sku.trim()||null,serialNumber:form.serialNumber.trim()||null,description:form.description.trim()||null,notes:form.notes.trim()||null,purchasePrice:money(form.purchasePrice),medianValue:money(form.medianValue),suggestedPrice:money(form.suggestedPrice),minimumPrice:money(form.minimumPrice),specifics:{...form.specifics,storagePath:form.storagePath.trim(),tags:JSON.stringify(form.tags.split(',').map(v=>v.trim()).filter(Boolean)),photos:JSON.stringify(form.photos),__protectedFields:JSON.stringify([...new Set(form.protectedFields)].sort()),__inferredFields:JSON.stringify([...new Set(form.inferredFields)].sort())}}};
export function validateItemForm(form:ItemFormState):string[]{const e:string[]=[];if(!form.title.trim())e.push('Title is required.');if(!form.category.trim())e.push('Category is required.');if(!form.condition.trim())e.push('Condition is required.');if(form.year&&(!/^\d{1,4}$/.test(form.year)||Number(form.year)>9999))e.push('Year must be a valid 1–4 digit year.');if(Number(form.quantity)<1)e.push('Quantity must be at least 1.');return e;}
