import type{ItemRecord}from'@vault/domain';import type{ComparableProvider,ProviderId,ProviderResult}from'@vault/marketplace';import type{SaleComparable}from'@vault/pricing';
export type CredentialState='not-configured'|'configured'|'invalid';export type AdapterHealth='ready'|'credentials-required'|'rate-limited'|'offline'|'error';export type AdapterContext={fetchFn?:typeof fetch;credentialRef?:string;signal?:AbortSignal;currency?:string};
export interface PricingAdapter extends ComparableProvider{displayName:string;credentialState:CredentialState;supports(item:ItemRecord):boolean;ttlMs(item:ItemRecord):number;health(context?:AdapterContext):Promise<AdapterHealth>;searchItem(item:ItemRecord,context?:AdapterContext):Promise<ProviderResult>}
export type CacheEntry={key:string;provider:ProviderId;createdAt:string;expiresAt:string;result:ProviderResult};
const normalize=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,' ');const id=(p:string)=>`${p}_${Math.random().toString(36).slice(2)}`;
export function buildCacheKey(provider:ProviderId,item:ItemRecord,currency='USD'):string{return[provider,normalize(item.title),normalize(item.condition),currency.toUpperCase(),item.sku??'',item.model??'',item.specifics.barcode??''].join('|')}
export function routeProviders(item:ItemRecord,available:ProviderId[]=['ebay','tcgplayer','pricecharting','discogs','manual']):ProviderId[]{const text=`${item.category} ${item.subcategory??''}`.toLowerCase();const preferred:ProviderId[]=/card|pokemon|yugioh|magic/.test(text)?['tcgplayer','ebay']:/game|console/.test(text)?['pricecharting','ebay']:/vinyl|record|cd|cassette|music/.test(text)?['discogs','ebay']:['ebay','manual'];return preferred.filter(p=>available.includes(p))}
const num=(v:unknown)=>Number.isFinite(Number(v))?Math.round(Number(v)*100):0;const comparable=(provider:ProviderId,row:any,fields:{title:string;price:unknown;shipping?:unknown;condition?:string;soldAt?:string;url?:string}):SaleComparable=>({id:String(row.id??id(provider)),provider,title:fields.title,soldAmountMinor:num(fields.price),shippingMinor:num(fields.shipping??0),quantity:Number(row.quantity??1),condition:fields.condition??null,soldAt:fields.soldAt??null,url:fields.url??null});
export function normalizeEbay(payload:any):SaleComparable[]{const rows=payload.itemSummaries??payload.items??[];return rows.map((r:any)=>comparable('ebay',r,{title:r.title??'',price:r.price?.value??r.soldPrice?.value??0,shipping:r.shippingOptions?.[0]?.shippingCost?.value??0,condition:r.condition,soldAt:r.itemEndDate,url:r.itemWebUrl})).filter((r:SaleComparable)=>r.title&&r.soldAmountMinor>0)}
export function normalizeTcgplayer(payload:any):SaleComparable[]{const rows=payload.results??payload.data??[];return rows.map((r:any)=>comparable('tcgplayer',r,{title:[r.productName,r.setName,r.printing].filter(Boolean).join(' '),price:r.marketPrice??r.lowPrice??r.price??0,condition:r.condition,url:r.url})).filter((r:SaleComparable)=>r.title&&r.soldAmountMinor>0)}
export function normalizePriceCharting(payload:any):SaleComparable[]{const rows=Array.isArray(payload)?payload:payload.products??payload.results??[payload];return rows.flatMap((r:any)=>[['loose-price','Loose'],['cib-price','Complete'],['new-price','New'],['graded-price','Graded']].map(([k,c])=>comparable('pricecharting',{id:`${r.id??id('pc')}-${k}`},{title:`${r['product-name']??r.name??''} ${c}`,price:Number(r[k]??0)/100,condition:c,url:r.url}))).filter((r:SaleComparable)=>r.title&&r.soldAmountMinor>0)}
export function normalizeDiscogs(payload:any):SaleComparable[]{const rows=payload.results??payload.listings??[];return rows.map((r:any)=>comparable('discogs',r,{title:r.title??r.release?.description??'',price:r.price?.value??r.lowest_price??0,shipping:r.shipping_price?.value??0,condition:r.condition,url:r.uri})).filter((r:SaleComparable)=>r.title&&r.soldAmountMinor>0)}
export function classifyProviderError(error:unknown):AdapterHealth{const text=String(error).toLowerCase();if(/401|403|credential|unauthor/.test(text))return'credentials-required';if(/429|rate limit/.test(text))return'rate-limited';if(/offline|network|failed to fetch/.test(text))return'offline';return'error'}
export function computeBackoffMs(attempt:number,base=1000,max=60000,jitter=0.2):number{const raw=Math.min(max,base*2**Math.max(0,attempt));return Math.round(raw*(1-jitter/2+Math.random()*jitter))}
export function redactSecrets(value:string):string{return value.replace(/Authorization\s*:\s*Bearer\s+[A-Za-z0-9._~-]+/gi,'Authorization: Bearer [REDACTED]').replace(/Bearer\s+[A-Za-z0-9._~-]+/gi,'Bearer [REDACTED]').replace(/(token|api[_-]?key|client[_-]?secret)\s*[:=]\s*[^\s,;]+/gi,'$1=[REDACTED]')}
export class PricingCache{private entries=new Map<string,CacheEntry>();get(key:string,allowStale=false):{entry:CacheEntry;stale:boolean}|null{const entry=this.entries.get(key);if(!entry)return null;const stale=Date.parse(entry.expiresAt)<=Date.now();return stale&&!allowStale?null:{entry,stale}}set(key:string,provider:ProviderId,result:ProviderResult,ttlMs:number):CacheEntry{const createdAt=new Date().toISOString();const entry={key,provider,createdAt,expiresAt:new Date(Date.now()+ttlMs).toISOString(),result};this.entries.set(key,entry);return entry}clear(provider?:ProviderId){if(!provider)this.entries.clear();else for(const[k,v]of this.entries)if(v.provider===provider)this.entries.delete(k)}}
type OfficialConfig={id:ProviderId;displayName:string;endpoint:string;credentialState:CredentialState;normalize:(payload:any)=>SaleComparable[];supports?:(item:ItemRecord)=>boolean;ttlMs?:number};
export class OfficialApiAdapter implements PricingAdapter{id:ProviderId;displayName:string;credentialState:CredentialState;constructor(private config:OfficialConfig){this.id=config.id;this.displayName=config.displayName;this.credentialState=config.credentialState}supports(item:ItemRecord){return this.config.supports?.(item)??true}ttlMs(){return this.config.ttlMs??21600000}async health(){return this.credentialState==='configured'?'ready':'credentials-required'}async search(query:string,options?:{condition?:string|null;signal?:AbortSignal}):Promise<ProviderResult>{return this.searchRaw(query,{signal:options?.signal})}async searchItem(item:ItemRecord,context:AdapterContext={}):Promise<ProviderResult>{if(!this.supports(item))return{provider:this.id,health:'offline',comparables:[],message:'Unsupported category'};return this.searchRaw(item.title,context)}private async searchRaw(query:string,context:AdapterContext):Promise<ProviderResult>{if(this.credentialState!=='configured')return{provider:this.id,health:'credentials-required',comparables:[],message:'Configure provider credentials in secure storage'};try{const fetchFn=context.fetchFn??fetch;const response=await fetchFn(`${this.config.endpoint}${this.config.endpoint.includes('?')?'&':'?'}q=${encodeURIComponent(query)}`,{signal:context.signal,headers:context.credentialRef?{'X-Vault-Credential-Ref':context.credentialRef}:{}});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);const payload=await response.json();return{provider:this.id,health:'ready',comparables:this.config.normalize(payload)}}catch(error){const health=classifyProviderError(error);return{provider:this.id,health:health==='credentials-required'?'credentials-required':'error',comparables:[],message:redactSecrets(String(error))}}}}
export const createDefaultAdapters=(states:Partial<Record<ProviderId,CredentialState>>={}):OfficialApiAdapter[]=>[
new OfficialApiAdapter({id:'ebay',displayName:'eBay',endpoint:'https://api.ebay.com/buy/browse/v1/item_summary/search',credentialState:states.ebay??'not-configured',normalize:normalizeEbay,ttlMs:21600000}),
new OfficialApiAdapter({id:'tcgplayer',displayName:'TCGplayer',endpoint:'https://api.tcgplayer.com/catalog/products',credentialState:states.tcgplayer??'not-configured',normalize:normalizeTcgplayer,supports:i=>/card|pokemon|yugioh|magic/i.test(`${i.category} ${i.subcategory??''}`),ttlMs:43200000}),
new OfficialApiAdapter({id:'pricecharting',displayName:'PriceCharting',endpoint:'https://www.pricecharting.com/api/product',credentialState:states.pricecharting??'not-configured',normalize:normalizePriceCharting,supports:i=>/game|console/i.test(`${i.category} ${i.subcategory??''}`),ttlMs:86400000}),
new OfficialApiAdapter({id:'discogs',displayName:'Discogs',endpoint:'https://api.discogs.com/database/search',credentialState:states.discogs??'not-configured',normalize:normalizeDiscogs,supports:i=>/vinyl|record|cd|cassette|music/i.test(`${i.category} ${i.subcategory??''}`),ttlMs:43200000})];